package tree

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sparkrew/rechta/resolver"
)

func TestPrintHTML(t *testing.T) {
	trees := []resolver.WorkflowTree{
		{
			Path: ".github/workflows/ci.yml",
			Dependencies: []*resolver.DependencyNode{
				{
					Ref: resolver.ActionRef{
						Owner:   "actions",
						Repo:    "checkout",
						Ref:     "v4",
						RawUses: "actions/checkout@v4",
					},
					SHA:  "34e114876b0b11c390a56381ad16ebd13914f8d5",
					Type: resolver.ActionTypeNode,
					Children: []*resolver.DependencyNode{
						{
							Ref: resolver.ActionRef{
								Owner:   "actions",
								Repo:    "github-script",
								Ref:     "v7",
								RawUses: "actions/github-script@v7",
							},
							SHA:            "60a0d83039c74a4aee543508d2ffcb1c3799cdea",
							Type:           resolver.ActionTypeNode,
							AlreadyVisited: true,
							ContentSHA256:  "abc123",
							ContentPath:    "actions/checkout@v4/action.yml",
						},
					},
				},
			},
		},
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "report.html")

	if err := PrintHTML(trees, path); err != nil {
		t.Fatalf("PrintHTML: %v", err)
	}

	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read file: %v", err)
	}
	if len(b) == 0 {
		t.Fatal("expected non-empty HTML file")
	}

	html := string(b)
	checks := []string{
		"<!DOCTYPE html>",
		"rechta-data",
		`"workflows"`,
		".github/workflows/ci.yml",
		"actions/checkout@v4",
		"actions/github-script@v7",
		"already_visited",
		"content_sha256",
		"Generated by",
	}
	for _, want := range checks {
		if !strings.Contains(html, want) {
			t.Errorf("HTML missing %q", want)
		}
	}
}

func TestWalkDependencies(t *testing.T) {
	root := &resolver.DependencyNode{
		Ref: resolver.ActionRef{RawUses: "root"},
		Children: []*resolver.DependencyNode{
			{Ref: resolver.ActionRef{RawUses: "child"}},
		},
	}

	var order []string
	WalkDependencies([]*resolver.DependencyNode{root}, func(n *resolver.DependencyNode, depth int) {
		order = append(order, n.Ref.RawUses)
		if depth > 5 {
			t.Fatal("depth too large")
		}
	})

	if len(order) != 2 || order[0] != "root" || order[1] != "child" {
		t.Fatalf("walk order = %v, want [root child]", order)
	}
}
